version: '3'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      dockerfile: Dockerfile.dev

  weather:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
