version: '3'

services:
  apigateway:
    image: apigateway
    build:
      context: src/gw
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  spa:
    image: spa
    build:
      context: src/spa
      dockerfile: Dockerfile
    ports:
      - "5001:80"
 
  weather:
    image: weather
    build:
      context: src/weather
      dockerfile: Dockerfile
    ports:
      - "5002:80"
