FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /nodejs
ENV NODE_VERSION 8.9.4
ENV NODE_DOWNLOAD_SHA 21fb4690e349f82d708ae766def01d7fec1b085ce1f5ab30d9bda8ee126ca8fc
RUN curl -SL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" --output nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
    && rm nodejs.tar.gz \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY cNeuro.Spa.csproj .
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
RUN dotnet build -c Release -o /dist

FROM build as publish
RUN dotnet publish -c Release -o /dist

FROM base AS final
WORKDIR /dist
COPY --from=publish /dist .
EXPOSE 80
ENTRYPOINT ["dotnet", "cNeuro.Spa.dll"]
